# Vi-style copy mode
set -g mode-keys vi

# Better terminal colors
set -g default-terminal "tmux-256color"

# When selected press y to copy to system clipboard; leave Enter to sopy to tmux one
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"
